version: '3.4'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_DATABASE=D
      - MYSQL_ROOT_PASSWORD=123123*
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=123123*
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin','--transaction-isolation=READ-COMMITTED', '--innodb_log_file_size=256M', '--max_allowed_packet=256M']
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge

volumes:
  home_data:
    external: false
  mysql_data:
    external: false
