kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-springboot-app
  template:
    metadata:
      labels:
        app: openshift-springboot-app
    spec:
      containers:
        - name: openshift-java-springboot
          image: dotiendat1751998/student-docker:latest
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: openshift-springboot
spec:
  ports:
    - name: http-8082
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: openshift-springboot
